### ISSUE TITLE
Manyverse, Chrome and room_v2 Links broken

### ISSUE THREAD

**Issue by xundeenergie** [staltz/manyverse#103] opened 2021-11-09 13:33 UTC
Hi i sent an invitation from my new room version 2 to friends.
They can open the Link, but no Application can handle the ssb://-Link.

This happens with chrome-based Browsers (Chrome, Vivaldi) on Androids. "No ssb-App found".
With Firefox they can klick on the Link, and Manyverse opens.

**Comment by staltz** [comment] 2021-11-09 13:51
Thanks for the details. Sounds like an issue with go-ssb-room, and a duplicate of this one: https://github.com/ssb-ngi-pointer/go-ssb-room/issues/135

**Closed by staltz** 2021-11-09 13:51 UTC
